### ISSUE TITLE
NVRTCError: NVRTC_ERROR_COMPILATION (6)

### ISSUE THREAD

**Issue by VolkerH** [mritools/cupyimg#17]
Hi, 
I run into  NVRTC compilation errors when trying to run cupyimg.
I have an otherwise working cupy environment with cupy version `9.0.0b3`.
Cudatoolkit version is 11.2. This has been installed from conda forge.
I verified that I can create cupy arrays and do basic operations on them.

When trying to run the example code snippet from your README.md file the 
line `yg = uniform_filter(xg, size=5)` generates the following error:

```
yg = uniform_filter(xg, size=5)

​

---------------------------------------------------------------------------
NVRTCError                                Traceback (most recent call last)
~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py in compile(self, options, log_stream)
    624                     nvrtc.addAddNameExpression(self.ptr, ker)
--> 625             nvrtc.compileProgram(self.ptr, options)
    626             mapping = None

cupy_backends/cuda/libs/nvrtc.pyx in cupy_backends.cuda.libs.nvrtc.compileProgram()

cupy_backends/cuda/libs/nvrtc.pyx in cupy_backends.cuda.libs.nvrtc.compileProgram()

cupy_backends/cuda/libs/nvrtc.pyx in cupy_backends.cuda.libs.nvrtc.check_status()

NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

CompileException                          Traceback (most recent call last)
<ipython-input-5-e3ce52cf8d9c> in <module>
----> 1 yg = uniform_filter(xg, size=5)

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupyimg/scipy/ndimage/filters.py in uniform_filter(input, size, output, mode, cval, origin, dtype_mode)
    650     if len(axes) > 0:
    651         for axis, size, origin, mode in axes:
--> 652             uniform_filter1d(
    653                 input,
    654                 int(size),

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupyimg/scipy/ndimage/filters.py in uniform_filter1d(input, size, axis, output, mode, cval, origin, dtype_mode)
    595         raise ValueError("invalid origin")
    596     weights = cupy.full((size,), 1 / size, dtype=dtype_weights)
--> 597     return correlate1d(
    598         input, weights, axis, output, mode, cval, origin, dtype_mode=dtype_mode
    599     )

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupyimg/scipy/ndimage/filters.py in correlate1d(input, weights, axis, output, mode, cval, origin, backend, dtype_mode)
    256             input.ndim, weights, origin, axis
    257         )
--> 258         return _correlate_or_convolve(
    259             input, weights, output, mode, cval, origins, dtype_mode=dtype_mode
    260         )

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupyimg/scipy/ndimage/filters.py in _correlate_or_convolve(input, weights, output, mode, cval, origin, convolution, dtype_mode)
    490     offsets = _filters_core._origins_to_offsets(origins, weights.shape)
    491     kernel = _get_correlate_kernel(mode, weights.shape, int_type, offsets, cval)
--> 492     output = _filters_core._call_kernel(
    493         kernel, input, weights, output, weights_dtype=weights_dtype
    494     )

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupyimg/scipy/ndimage/_filters_core.py in _call_kernel(kernel, input, weights, output, structure, weights_dtype, structure_dtype)
    150         output, temp = _util._get_output(output.dtype, input), output
    151     args.append(output)
--> 152     kernel(*args)
    153     if needs_temp:
    154         temp[...] = output[...]

cupy/core/_kernel.pyx in cupy.core._kernel.ElementwiseKernel.__call__()

cupy/core/_kernel.pyx in cupy.core._kernel.ElementwiseKernel._get_elementwise_kernel()

cupy/_util.pyx in cupy._util.memoize.decorator.ret()

cupy/core/_kernel.pyx in cupy.core._kernel._get_elementwise_kernel()

cupy/core/_kernel.pyx in cupy.core._kernel._get_simple_elementwise_kernel()

cupy/core/_kernel.pyx in cupy.core._kernel._get_simple_elementwise_kernel()

cupy/core/core.pyx in cupy.core.core.compile_with_cache()

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py in compile_with_cache(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, jitify)
    432             name_expressions, log_stream, cache_in_memory)
    433     else:
--> 434         return _compile_with_cache_cuda(
    435             source, options, arch, cache_dir, extra_source, backend,
    436             enable_cooperative_groups, name_expressions, log_stream,

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py in _compile_with_cache_cuda(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, cache_in_memory, jitify)
    509     if backend == 'nvrtc':
    510         cu_name = '' if cache_in_memory else name + '.cu'
--> 511         ptx, mapping = compile_using_nvrtc(
    512             source, options, arch, cu_name, name_expressions,
    513             log_stream, cache_in_memory, jitify)

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py in compile_using_nvrtc(source, options, arch, filename, name_expressions, log_stream, cache_in_memory, jitify)
    271                 cu_file.write(source)
    272 
--> 273             return _compile(source, options, cu_path,
    274                             name_expressions, log_stream, jitify)
    275     else:

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py in _compile(source, options, cu_path, name_expressions, log_stream, jitify)
    255                              name_expressions=name_expressions)
    256         try:
--> 257             ptx, mapping = prog.compile(options, log_stream)
    258         except CompileException as e:
    259             dump = _get_bool_env_variable(

~/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/cuda/compiler.py in compile(self, options, log_stream)
    635         except nvrtc.NVRTCError:
    636             log = nvrtc.getProgramLog(self.ptr)
--> 637             raise CompileException(log, self.src, self.name, options,
    638                                    'nvrtc' if not runtime.is_hip else 'hiprtc')
    639 

CompileException: /home/hilsenst/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/core/include/cupy/complex/complex.h(94): warning: __host__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

/home/hilsenst/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/core/include/cupy/complex/complex.h(94): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

/home/hilsenst/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/core/include/cupy/complex/complex.h(101): warning: __host__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

/home/hilsenst/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/core/include/cupy/complex/complex.h(101): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

/home/hilsenst/miniconda3/envs/cupy/lib/python3.8/site-packages/cupy/core/include/cupy/carray.cuh(4): catastrophic error: cannot open source file "type_traits"

1 catastrophic error detected in the compilation of "/tmp/tmppb62rtd7/1077d7e392f07f825d24a432298f6244_2.cubin.cu".
Compilation terminated.

```

Note that I got the same error with every filter that I tried, so it is not specific to the example in the README.

I assume that this has something todo with the compiler used for compiling Cuda kernels (which I guess is part of cudatoolkit ?).

I observed this error a couple of months back when I first got  this machine (DELL XPS 15, GTX 1650, Ubuntu 20.04). Back then I thought this had something to do with the version of cudatoolkit I was using (there was no cudatoolkit 11.2 on conda-forge at the time). I had also tried installing cupyimg inside a RAPIDS docker container back then and got the same error. (other RAPIDS stuff seemed to be working). 
At the time I thought this may be due to some cudatoolkit version mismatch and I decided to wait for cudatoolkit 11.2. Now that it is available the error ist still here.

Any pointers would be appreciated.

In case it is important:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 165...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P8     3W /  N/A |   2141MiB /  3914MiB |     22%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

**Comment by leofang** [comment]
@VolkerH Thanks for testing it out and for reporting.

@grlee77 This is due to the CuPy bug just introduced recently: https://github.com/cupy/cupy/issues/4875. The temporary solution is to add `--std=c++11` to compiler options of `RawKernel`/`RawModule`, if it's used in cupyimg. I think this is a regression and should be fixed asap.

**Comment by VolkerH** [comment]
Thanks for that @leofang. If that is the case,  I will try reverting to an earlier version of cupy until the issue you mentioned is fixed upstream.

**Comment by VolkerH** [comment]
Ok, I just downgraded to `cupy` version `8.3.0` from conda-forge with python 3.7 and I also get an `NVRTCError`, but not the exact same one:

(also caused by the uniform_filter call in the snippet of the README.md file in this repo).

If these errors are related this would not be consistent with a recent regression in cupy, but  maybe these errors have different causes.

```
---------------------------------------------------------------------------
NVRTCError                                Traceback (most recent call last)
~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/cuda/compiler.py in compile(self, options, log_stream)
    553                     nvrtc.addAddNameExpression(self.ptr, ker)
--> 554             nvrtc.compileProgram(self.ptr, options)
    555             mapping = None

cupy_backends/cuda/libs/nvrtc.pyx in cupy_backends.cuda.libs.nvrtc.compileProgram()

cupy_backends/cuda/libs/nvrtc.pyx in cupy_backends.cuda.libs.nvrtc.compileProgram()

cupy_backends/cuda/libs/nvrtc.pyx in cupy_backends.cuda.libs.nvrtc.check_status()

NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

CompileException                          Traceback (most recent call last)
<ipython-input-1-63e2addd1a0a> in <module>
     14 # separable 5x5x5 convolution kernel on the GPU
     15 xg = cupy.asarray(x)
---> 16 yg = uniform_filter(xg, size=5)
     17 # %timeit yg = uniform_filter(xg, size=5); d.synchronize()
     18 #    -> 6.23 ms ± 24.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupyimg/scipy/ndimage/filters.py in uniform_filter(input, size, output, mode, cval, origin, dtype_mode)
    658                 cval,
    659                 origin,
--> 660                 dtype_mode=dtype_mode,
    661             )
    662             input = output

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupyimg/scipy/ndimage/filters.py in uniform_filter1d(input, size, axis, output, mode, cval, origin, dtype_mode)
    596     weights = cupy.full((size,), 1 / size, dtype=dtype_weights)
    597     return correlate1d(
--> 598         input, weights, axis, output, mode, cval, origin, dtype_mode=dtype_mode
    599     )
    600 

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupyimg/scipy/ndimage/filters.py in correlate1d(input, weights, axis, output, mode, cval, origin, backend, dtype_mode)
    257         )
    258         return _correlate_or_convolve(
--> 259             input, weights, output, mode, cval, origins, dtype_mode=dtype_mode
    260         )
    261     else:

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupyimg/scipy/ndimage/filters.py in _correlate_or_convolve(input, weights, output, mode, cval, origin, convolution, dtype_mode)
    491     kernel = _get_correlate_kernel(mode, weights.shape, int_type, offsets, cval)
    492     output = _filters_core._call_kernel(
--> 493         kernel, input, weights, output, weights_dtype=weights_dtype
    494     )
    495     return output

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupyimg/scipy/ndimage/_filters_core.py in _call_kernel(kernel, input, weights, output, structure, weights_dtype, structure_dtype)
    150         output, temp = _util._get_output(output.dtype, input), output
    151     args.append(output)
--> 152     kernel(*args)
    153     if needs_temp:
    154         temp[...] = output[...]

cupy/core/_kernel.pyx in cupy.core._kernel.ElementwiseKernel.__call__()

cupy/core/_kernel.pyx in cupy.core._kernel.ElementwiseKernel._get_elementwise_kernel()

cupy/_util.pyx in cupy._util.memoize.decorator.ret()

cupy/core/_kernel.pyx in cupy.core._kernel._get_elementwise_kernel()

cupy/core/_kernel.pyx in cupy.core._kernel._get_simple_elementwise_kernel()

cupy/core/_kernel.pyx in cupy.core._kernel._get_simple_elementwise_kernel()

cupy/core/core.pyx in cupy.core.core.compile_with_cache()

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/cuda/compiler.py in compile_with_cache(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream)
    374             source, options, arch, cache_dir, extra_source, backend,
    375             enable_cooperative_groups, name_expressions, log_stream,
--> 376             cache_in_memory)
    377 
    378 

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/cuda/compiler.py in _compile_with_cache_cuda(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, cache_in_memory)
    440         ptx, mapping = compile_using_nvrtc(
    441             source, options, arch, cu_name, name_expressions,
--> 442             log_stream, cache_in_memory)
    443         if _is_cudadevrt_needed(options):
    444             # for separate compilation

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/cuda/compiler.py in compile_using_nvrtc(source, options, arch, filename, name_expressions, log_stream, cache_in_memory)
    210 
    211             return _compile(source, options, cu_path,
--> 212                             name_expressions, log_stream)
    213     else:
    214         return _compile(source, options, '', name_expressions, log_stream)

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/cuda/compiler.py in _compile(source, options, cu_path, name_expressions, log_stream)
    193                              name_expressions=name_expressions)
    194         try:
--> 195             ptx, mapping = prog.compile(options, log_stream)
    196         except CompileException as e:
    197             dump = _get_bool_env_variable(

~/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/cuda/compiler.py in compile(self, options, log_stream)
    564             log = nvrtc.getProgramLog(self.ptr)
    565             raise CompileException(log, self.src, self.name, options,
--> 566                                    'nvrtc' if not runtime.is_hip else 'hiprtc')
    567 
    568 

CompileException: /home/hilsenst/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/core/include/cupy/complex/complex.h(94): warning: __host__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

/home/hilsenst/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/core/include/cupy/complex/complex.h(94): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

/home/hilsenst/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/core/include/cupy/complex/complex.h(101): warning: __host__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

/home/hilsenst/miniconda3/envs/cupy830/lib/python3.7/site-packages/cupy/core/include/cupy/complex/complex.h(101): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

/tmp/tmpkc7qafah/1e83c354aece002849c8a6558ec6f5b2_2.cubin.cu(9): catastrophic error: cannot open source file "math_constants.h"

1 catastrophic error detected in the compilation of "/tmp/tmpkc7qafah/1e83c354aece002849c8a6558ec6f5b2_2.cubin.cu".
Compilation terminated.
```

**Comment by leofang** [comment]
That's another bug that we've fixed in v8.4 or v8.5 😆

**Comment by grlee77** [comment]
Thanks for linking those issues, @leofang. 

@VolkerH: CuPy 9.0 will have most, if not all, things that were under the `cupyimg.numpy` and `cupyimg.scipy` namespaces here. 

The things currently unique to this repository are in the `cupyimg.skimage` namespace, although these are also in the process of moving to a new home where they will be better tested and should hopefully be more reliable long term. I will put a link to that repository and probably archive this one once everything is public (mid-to-late April). The API will remain the same as what is here (matching scikit-image), but the top-level package name will change.

**Comment by grlee77** [comment]
I merged #18 which should make things compatible with CuPy 9.0.0b3 again. It will likely still not work with 8.x, although that apparently already wasn't working. 

We will be targeting the new repository to CuPy >= 9 only so that we don't have to duplicate a lot of the functionality that was already ported upstream.

**Comment by VolkerH** [comment]
Hi @grlee77, 

I installed the latest master following #18, but unfortunately I still get the same compilation error as in the original post in this issue. Not sure whether this is expected (i.e. waiting for upstream fix as indicated by @leofang) or whether there is something wrong with the toolchain on my machine (or in my conda env).

**Comment by VolkerH** [comment]
BTW, nice to hear about a lot of the `scipy` and `numpy` functionality here moving into `cupy`.

**Comment by grlee77** [comment]
> I installed the latest master following #18, but unfortunately I still get the same compilation error as in the original post in this issue. 

I tried running the tests again today (on CUDA 11.0) using the conda-forge 9.0.0b3 package instead of a local build and did get some compilation errors related to `math_constants.h`. I just merged 4f5b458 which backports the fix for this from upstream CuPy. This would require a fairly recent CuPy as I don't think older versions had a local copy of the necessary constants.

Also, the new package I mentioned should be public by the time of [this GTC presentation related to it](https://gtc21.event.nvidia.com/media/cuCIM%3A%20A%20GPU%20Image%20I_O%20and%20Processing%20Toolkit%20%5BS32194%5D/1_gs9sakht)

**Comment by VolkerH** [comment]
Hooray. After cloning the repo and installing from the latest master no more error message with cupy 9.0.0b3 from conda-forge.
Thanks for fixing this.

It took me two attempts though, on first attempt I was installing like this:
```
pip install https://github.com/mritools/cupyimg/archive/master.zip
```
and either some local caching on my machine or some caching at github (zipfile generation) threw a spanner in the works. 

I guess this issue can be closed now, and once the new package becomes public it will probably be obsolete anyway.
I'll leave the decision up to you.

**Comment by leofang** [comment]
The fix is merged upstream: https://github.com/cupy/cupy/pull/4922.

**Comment by grlee77** [comment]
To follow up on my previous comment:

The newer version of this repository is now a RAPIDS project called [cuCIM](https://github.com/rapidsai/cucim). The `cucim.skimage` module there is an updated version of `cupyimg.skimage` from this repository. In addition, new image I/O functionality mirroring the OpenSlide API is available via a `cucim.clara` module (initially supporting TIFF files, but more formats are planned in the future). 

Currently, it should be possible to install for CUDA 11.x via conda from the `rapidsai-nightly` channel. For example, to create a new conda environment with it:

```bash
conda create -n cucim -c rapidsai-nightly -c conda-forge/label/cupy_rc -c conda-forge cucim
conda activate cucim
```

In a few days it should be ready on the main `rapidsai` channel as well. If you try it and encounter any problems, please let us know over at the [cuCIM issues page](https://github.com/rapidsai/cucim/issues).

One known issue at the moment is that cuCIM requires a newer version of CuPy than other RAPIDS projects. For a future RAPIDS 0.20 release, I think the whole RAPIDS ecosystem will have updated to CuPy 9.0, making things easier to install together in the same environment.

**Comment by leofang** [comment]
Thank you for the update, @grlee77! Glad to hear it lands in a new home! Congrats for you 🙂

**Comment by DAVID-Hown** [comment]
@grlee77 
Hello, I have also encountered the same problem. This error occurred when I was running other people's demo examples. This problem has bothered me for many days.
error：
Number of threads used:  32
Loading models parameters...
./models/trained/disparity-estimation-no-mask.tar
Model disparity loaded succesfully.
./models/trained/disparity-refinement.tar
Model refine loaded succesfully.
./models/trained/inpainting-color.tar
Model inpaint loaded succesfully.
Traceback (most recent call last):
  File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 681, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 139, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 151, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 67, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/DATA/jupyter/share/haodawei/improved-kbe/kbe.py", line 182, in <module>
    ken_burn_pipe((tensorImage+1)/2, zoom_settings, output_path, pretrained_estim=pretrained_estim)
  File "/DATA/jupyter/share/haodawei/improved-kbe/utils/pipeline.py", line 112, in __call__
    numpyResult = process_kenburns({
  File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 208, in process_kenburns
    tensorRender, tensorExisting = render_pointcloud(objectCommon['tensorInpaPoints'] + tensorShift, 
  File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 435, in render_pointcloud
    launch_kernel('kernel_pointrender_updateZee', preprocess_kernel('''
  File "cupy/_util.pyx", line 67, in cupy._util.memoize.decorator.ret
  File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 380, in launch_kernel
    return cupy.cuda.compile_with_cache(strKernel, tuple([ '-I ' + os.environ['CUDA_HOME'], '-I ' + os.environ['CUDA_HOME'] + '/include' ])).get_function(strFunction)
  File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 460, in compile_with_cache
    return _compile_module_with_cache(*args, **kwargs)
  File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 488, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 566, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 317, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 301, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 698, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /tmp/tmpl94lnfh3/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu(2): catastrophic error: cannot open source file "/home/s182169/Master_thesis/GAN-Burns-effect/utils/helper_math.h"

1 catastrophic error detected in the compilation of "/tmp/tmpl94lnfh3/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu".
Compilation terminated.
————————————————
my env:
OS                           : Linux-4.9.0-8-amd64-x86_64-with-glibc2.27
Python Version               : 3.9.2
CuPy Version                 : 10.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.20.1
SciPy Version                : 1.6.1
Cython Build Version         : 0.29.24
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 10020
CUDA Driver Version          : 10020
CUDA Runtime Version         : 10020
cuBLAS Version               : 10203
cuFFT Version                : 10102
cuRAND Version               : 10102
cuSOLVER Version             : (10, 3, 0)
cuSPARSE Version             : 10301
NVRTC Version                : (10, 2)
Thrust Version               : 100907
CUB Build Version            : 100800
Jitify Build Version         : 60e9e72
cuDNN Build Version          : 8300
cuDNN Version                : 8101
NCCL Build Version           : 21104
NCCL Runtime Version         : 2804
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:18:00.0
Device 1 Name                : Tesla V100-SXM2-32GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:3B:00.0
Device 2 Name                : Tesla V100-SXM2-32GB
Device 2 Compute Capability  : 70
Device 2 PCI Bus ID          : 0000:AF:00.0

**Comment by VolkerH** [comment]
Did you try https://github.com/rapidsai/cucim or cupyimg (which has been superseeded by cucim)?

**Comment by DAVID-Hown** [comment]
@VolkerH 
Thank you for your reply. I have not tried cucim. If I want to use cucim, do I need to modify some codes under CUPY before?
I am a novice, in the running code found in the code about cupy code, would like to ask you?

**Comment by VolkerH** [comment]
If you have existing code that is based on cupyimg and cupy you may have to change imports as the package is now called `cucim` and some functions have been moved to `cupy` itself. See the top of the README.md here in this repo.

**Comment by DAVID-Hown** [comment]
@VolkerH 
I was just looking at my code, and THERE's a reference in there：
launch_kernel('kernel_pointrender_updateZee', preprocess_kernel('''
		extern "C" __global__ void kernel_pointrender_updateZee(
			const int n,
			const float* input,
			const float* data,
			const float* zee
		) { for (int intIndex = (blockIdx.x * blockDim.x) + threadIdx.x; intIndex < n; intIndex += blockDim.x * gridDim.x) {
			const int intSample = ( intIndex / SIZE_2(input) ) % SIZE_0(input);
			const int intPoint  = ( intIndex                 ) % SIZE_2(input);

			assert(SIZE_1(input) == 3);
			assert(SIZE_1(zee) == 1);

			float3 dblPlanePoint = make_float3(0.0, 0.0, {{dblFocal}});
			float3 dblPlaneNormal = make_float3(0.0, 0.0, 1.0);

			float3 dblLinePoint = make_float3(VALUE_3(input, intSample, 0, intPoint), VALUE_3(input, intSample, 1, intPoint), VALUE_3(input, intSample, 2, intPoint));
			float3 dblLineVector = make_float3(0.0, 0.0, 0.0) - dblLinePoint;

			if (dblLinePoint.z < 0.001) {
				return;
			}

			float dblNumerator = dot(dblPlanePoint - dblLinePoint, dblPlaneNormal);
			float dblDenominator = dot(dblLineVector, dblPlaneNormal);
			float dblDistance = dblNumerator / dblDenominator;

			if (fabs(dblDenominator) < 0.001) {
				return;
			}

			float3 dblIntersection = dblLinePoint + (dblDistance * dblLineVector); // https://en.wikipedia.org/wiki/Line%E2%80%93plane_intersection

			float dblOutputX = dblIntersection.x + (0.5 * SIZE_3(zee)) - 0.5;
			float dblOutputY = dblIntersection.y + (0.5 * SIZE_2(zee)) - 0.5;

			float dblError = 1000000.0 - (({{dblFocal}} * {{dblBaseline}}) / (dblLinePoint.z + 0.0000001));

			int intNorthwestX = (int) (floor(dblOutputX));
			int intNorthwestY = (int) (floor(dblOutputY));
			int intNortheastX = intNorthwestX + 1;
			int intNortheastY = intNorthwestY;
			int intSouthwestX = intNorthwestX;
			int intSouthwestY = intNorthwestY + 1;
			int intSoutheastX = intNorthwestX + 1;
			int intSoutheastY = intNorthwestY + 1;

			float dblNorthwest = (intSoutheastX - dblOutputX)    * (intSoutheastY - dblOutputY);
			float dblNortheast = (dblOutputX    - intSouthwestX) * (intSouthwestY - dblOutputY);
			float dblSouthwest = (intNortheastX - dblOutputX)    * (dblOutputY    - intNortheastY);
			float dblSoutheast = (dblOutputX    - intNorthwestX) * (dblOutputY    - intNorthwestY);

			if ((dblNorthwest >= dblNortheast) & (dblNorthwest >= dblSouthwest) & (dblNorthwest >= dblSoutheast)) {
				if ((intNorthwestX >= 0) & (intNorthwestX < SIZE_3(zee)) & (intNorthwestY >= 0) & (intNorthwestY < SIZE_2(zee))) {
					atomicMin(&zee[OFFSET_4(zee, intSample, 0, intNorthwestY, intNorthwestX)], dblError);
				}

			} else if ((dblNortheast >= dblNorthwest) & (dblNortheast >= dblSouthwest) & (dblNortheast >= dblSoutheast)) {
				if ((intNortheastX >= 0) & (intNortheastX < SIZE_3(zee)) & (intNortheastY >= 0) & (intNortheastY < SIZE_2(zee))) {
					atomicMin(&zee[OFFSET_4(zee, intSample, 0, intNortheastY, intNortheastX)], dblError);
				}

			} else if ((dblSouthwest >= dblNorthwest) & (dblSouthwest >= dblNortheast) & (dblSouthwest >= dblSoutheast)) {
				if ((intSouthwestX >= 0) & (intSouthwestX < SIZE_3(zee)) & (intSouthwestY >= 0) & (intSouthwestY < SIZE_2(zee))) {
					atomicMin(&zee[OFFSET_4(zee, intSample, 0, intSouthwestY, intSouthwestX)], dblError);
				}

			} else if ((dblSoutheast >= dblNorthwest) & (dblSoutheast >= dblNortheast) & (dblSoutheast >= dblSouthwest)) {
				if ((intSoutheastX >= 0) & (intSoutheastX < SIZE_3(zee)) & (intSoutheastY >= 0) & (intSoutheastY < SIZE_2(zee))) {
					atomicMin(&zee[OFFSET_4(zee, intSample, 0, intSoutheastY, intSoutheastX)], dblError);
				}

			}
		} }

**Comment by DAVID-Hown** [comment]
run python kbe.py in https://github.com/pierlj/ken-burns-effect
found error：
!CUDA_AVAILABLE_DEVICES=0 python kbe.py --in ./images/doublestrike.jpg --out ./videos/test_1.mp4 --estim-path ./models/trained/disparity-estimation-no-mask.tar --refine-path ./models/trained/disparity-refinement.tar --inpaint-path ./models/trained/inpainting-color.tar --write-frames --startU 512 --startV 512 --endU 600 --endV 600 --startW 400 --startH 200 --endW 300 --endH 150

**Comment by DAVID-Hown** [comment]
@VolkerH 
I am not familiar with this cupy programming for the first time. Could you please give me some advice？

**Comment by VolkerH** [comment]
Sorry, I am not a cupy expert either, I just wanted to point out the fact that this version is no longer current.

**Comment by leofang** [comment]
```
cupy.cuda.compiler.CompileException: /tmp/tmpl94lnfh3/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu(2): catastrophic error: cannot open source file "/home/s182169/Master_thesis/GAN-Burns-effect/utils/helper_math.h"
```
One of your project dependencies (`/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py`) hard-coded this header path. I don't think this is a problem in either CuPy or cupyimg.

**Comment by DAVID-Hown** [comment]
Thank you very much for your answer. I have carefully checked my C++ file path, and the path I referenced was wrong。


| |
郝大为
|
|
***@***.***
|
签名由网易邮箱大师定制


On 03/11/2022 15:34，Leo ***@***.***> wrote：

cupy.cuda.compiler.CompileException: /tmp/tmpl94lnfh3/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu(2): catastrophic error: cannot open source file "/home/s182169/Master_thesis/GAN-Burns-effect/utils/helper_math.h"


One of your project dependencies (/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py) hard-coded this header path. I don't think this is a problem in either CuPy or cupyimg.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
